[versions]
agp = "8.13.1"

hilt = "2.57.2"

kotlin = "2.2.21"
ksp = "2.3.2"

paging = "3.3.6"

room="2.8.3"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.11.0" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.4" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.9.4" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.11.00" }

androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material3-expressive = { module = "androidx.xr.compose.material3:material3", version = "1.0.0-alpha12" }
androidx-material3-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material3-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.9.6" }
androidx-navigation-runtime-android = { module = "androidx.navigation:navigation-runtime-android", version= "2.9.6" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }

androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version = "1.3.3" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.3.0" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.3.0" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version = "2.0.0" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.2" }

ksp-poet = { module = "com.squareup:kotlinpoet-ksp", version = "2.2.0" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version = "1.9.5" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

convention-android-library = { id = "convention.android.library", version = "" }

dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }

maven-publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
